apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: 57d21pwi6-java-springboot
  janus-idp.io/tekton: 57d21pwi6-java-springboot
  backstage.io/kubernetes-id: 57d21pwi6-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: 57d21pwi6-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
